In [93]:
import pandas as pd
import plotly.plotly as py
import plotly.graph_objs as go

In [94]:
df = pd.read_excel(r'C:\Users\belewaut\Downloads\20210829_coolblue_raw_data_Telefonie.xlsx')

In [95]:
df['price'] = df['price'].str.replace(r'-','')
df['price'] = df['price'].str.rstrip(',')
df['price'] = df['price'].str.rstrip(' ')
df['price'].head(10)

0     1.799
1     1.049
2       489
3    863,99
4       449
5    503,99
6    955,92
7       779
8    798,93
9       439
Name: price, dtype: object

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2552 entries, 0 to 2551
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_description  2552 non-null   object
 1   price                2552 non-null   object
 2   rating               2552 non-null   float64
 3   amount_reviews       2552 non-null   object
 4   product_category     2552 non-null   object
 5   product_class        2552 non-null   object
 6   date_of_scrape       2552 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(5)
memory usage: 139.7+ KB

In [97]:
df["amount_reviews"] = df['amount_reviews'].str.replace(r' reviews','')
df["product_category"] = df["product_category"].str.replace(r'mobiele-telefoons','smartphones')
df["rating"] = pd.to_numeric(df['rating'], errors = 'coerce')

In [98]:
df["amount_reviews"] = df['amount_reviews'].str.replace(r'1 review','1')
df["amount_reviews"] = df['amount_reviews'].fillna(0.0).astype(int)

In [99]:
df.head(20)

,product_description,price,rating,amount_reviews,product_category,product_class,date_of_scrape
0,Samsung Galaxy Z Fold 3 256GB Zwart 5G,1.799,5.0,2,smartphones,telefonie,2021-08-29 19:21:43.493
1,Samsung Galaxy Z Flip 3 128GB Zwart 5G,1.049,0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493
2,Samsung Galaxy S20 FE 128GB Blauw 4G,489,4.5,331,smartphones,telefonie,2021-08-29 19:21:43.493
3,Apple iPhone 12 128GB Zwart + Apple Usb C Opla...,"863,99",4.5,408,smartphones,telefonie,2021-08-29 19:21:43.493
4,Samsung Galaxy A52s 128GB Groen 5G,449,0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493
5,Apple iPhone SE 64GB Zwart + Apple Usb C Oplad...,"503,99",4.5,999,smartphones,telefonie,2021-08-29 19:21:43.493
6,Apple iPhone 12 128GB Zwart + Accessoirepakket...,"955,92",0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493
7,Samsung Galaxy S21 128GB Grijs 5G,779,4.5,112,smartphones,telefonie,2021-08-29 19:21:43.493
8,Apple iPhone 11 128 GB Zwart + Accessoirepakket,"798,93",0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493
9,Samsung Galaxy A72 128GB Zwart,439,4.5,96,smartphones,telefonie,2021-08-29 19:21:43.493
10,Apple iPhone SE 128GB Zwart + Apple Usb C Opla...,"553,99",4.5,999,smartphones,telefonie,2021-08-29 19:21:43.493
11,Apple iPhone 12 mini 128GB Zwart + Apple Usb C...,"773,99",4.5,352,smartphones,telefonie,2021-08-29 19:21:43.493
12,Samsung Galaxy S21 128GB Grijs 5G + Samsung Sn...,"803,99",4.5,112,smartphones,telefonie,2021-08-29 19:21:43.493
13,Samsung Galaxy S21 Ultra 256GB Zwart 5G + Sams...,"1.193,99",4.5,90,smartphones,telefonie,2021-08-29 19:21:43.493
14,Apple iPhone SE 128 GB Zwart,529,4.5,999,smartphones,telefonie,2021-08-29 19:21:43.493
15,Apple iPhone 12 128GB Zwart,839,4.5,408,smartphones,telefonie,2021-08-29 19:21:43.493
16,Apple iPhone 12 64GB Zwart + Apple Usb C Oplad...,"833,99",4.5,408,smartphones,telefonie,2021-08-29 19:21:43.493
17,Apple iPhone 12 128GB Zwart + Accessoirepakket,"915,93",0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493
18,Apple iPhone 11 64 GB Zwart + Otterbox Clearly...,"703,99",4.5,1391,smartphones,telefonie,2021-08-29 19:21:43.493
19,Samsung Galaxy S21 Ultra 256 GB Zwart 5G,1.169,4.5,90,smartphones,telefonie,2021-08-29 19:21:43.493

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2552 entries, 0 to 2551
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_description  2552 non-null   object
 1   price                2552 non-null   object
 2   rating               2552 non-null   float64
 3   amount_reviews       2552 non-null   int32
 4   product_category     2552 non-null   object
 5   product_class        2552 non-null   object
 6   date_of_scrape       2552 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int32(1), object(4)
memory usage: 129.7+ KB

In [101]:
df.head()

,product_description,price,rating,amount_reviews,product_category,product_class,date_of_scrape
0,Samsung Galaxy Z Fold 3 256GB Zwart 5G,1.799,5.0,2,smartphones,telefonie,2021-08-29 19:21:43.493
1,Samsung Galaxy Z Flip 3 128GB Zwart 5G,1.049,0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493
2,Samsung Galaxy S20 FE 128GB Blauw 4G,489,4.5,331,smartphones,telefonie,2021-08-29 19:21:43.493
3,Apple iPhone 12 128GB Zwart + Apple Usb C Opla...,"863,99",4.5,408,smartphones,telefonie,2021-08-29 19:21:43.493
4,Samsung Galaxy A52s 128GB Groen 5G,449,0.0,0,smartphones,telefonie,2021-08-29 19:21:43.493

In [102]:
df["price"] = df['price'].str.replace(r'.','')
df["price"] = df['price'].str.replace(r',','.')
df["price"] = pd.to_numeric(df['price'], errors = 'raise')

In [103]:
df["date_of_scrape"] = df['date_of_scrape'].dt.strftime("%d/%m/%y")

In [104]:
df["product_category"].unique()

array(['smartphones', 'vaste-telefoons', 'telefoonhoesjes',
       'screenprotectors/screenprotectors-voor-smartphones',
       'kabels-adapters-laders', 'horloges',
       'mobiele-telefoon-accessoires'], dtype=object)

In [105]:
df.drop(columns=["product_class","date_of_scrape"])

,product_description,price,rating,amount_reviews,product_category
0,Samsung Galaxy Z Fold 3 256GB Zwart 5G,1799.00,5.0,2,smartphones
1,Samsung Galaxy Z Flip 3 128GB Zwart 5G,1049.00,0.0,0,smartphones
2,Samsung Galaxy S20 FE 128GB Blauw 4G,489.00,4.5,331,smartphones
3,Apple iPhone 12 128GB Zwart + Apple Usb C Opla...,863.99,4.5,408,smartphones
4,Samsung Galaxy A52s 128GB Groen 5G,449.00,0.0,0,smartphones
...,...,...,...,...,...
2547,Belkin Autolader zonder Kabel Usb C 18W Power ...,24.99,5.0,2,mobiele-telefoon-accessoires
2548,PanzerGlass Privacy Camslider Apple iPhone X /...,27.99,4.0,6,mobiele-telefoon-accessoires
2549,Samsung Galaxy Buds 2 Groen,149.00,0.0,0,mobiele-telefoon-accessoires
2550,Azuri Wallet Xiaomi Redmi 9T Book Case Zwart,21.95,4.0,6,mobiele-telefoon-accessoires
2551,Kenu Airbase Pro Autohouder Universeel Zwart,29.99,5.0,11,mobiele-telefoon-accessoires

In [106]:
df_test = df['product_category']=='smartphones'

In [107]:
df = df[df_test]

In [108]:
df[['brand', 'product_description']] = df['product_description'].str.split(' ', 1, expand=True)

In [109]:
df.tail(10)

,product_description,price,rating,amount_reviews,product_category,product_class,date_of_scrape,brand
430,Galaxy Z Fold 3 256GB Groen 5G,1799.00,5.0,2,smartphones,telefonie,29/08/21,Samsung
431,Galaxy S21 Ultra 128GB Zwart 5G + Samsung Snel...,1103.99,4.5,90,smartphones,telefonie,29/08/21,Samsung
432,Galaxy A72 128GB Paars,439.00,4.5,96,smartphones,telefonie,29/08/21,Samsung
433,Smart.3 Mini Zwart,146.99,4.0,7,smartphones,telefonie,29/08/21,Emporia
434,Galaxy S21 Ultra 512GB Zilver 5G,1399.00,4.5,90,smartphones,telefonie,29/08/21,Samsung
435,Galaxy Z Flip 3 128GB Crème 5G + Samsung Draad...,1058.00,0.0,0,smartphones,telefonie,29/08/21,Samsung
436,S4 32GB Zwart,179.00,0.0,0,smartphones,telefonie,29/08/21,Emporia
437,Nord 256GB Grijs 5G + OnePlus Nord Sandstone B...,444.99,4.5,1006,smartphones,telefonie,29/08/21,OnePlus
438,Euphoria Senioren Telefoon,62.99,4.0,75,smartphones,telefonie,29/08/21,Emporia
439,Galaxy Z Fold 3 512GB Zwart 5G,1899.00,5.0,2,smartphones,telefonie,29/08/21,Samsung

In [111]:
df['brand'].unique()

array(['Samsung', 'Apple', 'OnePlus', 'MagSafe', 'OPPO', 'Sony',
       'Motorola', 'Xiaomi', 'Nokia', 'Starterspakket', 'Cat', 'CAT',
       'Fysic', 'CrossCall', 'Emporia'], dtype=object)